name:                monadic-semantic-calculus
version:             0.1.0.0
homepage: "https://gitlab.di.unipmn.it/20041679/monadic-semantic-calculus"
license:             BSD-3-Clause
author:              "20051799"
maintainer:          "20051799@studenti.uniupo.com"
# copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
# description:         Please see the README on GitHub at <https://github.com/githubuser/monadic-semantic-calculus#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - Lib
    - Effects.Nondeterminism

executables:
  monadic-semantic-calculus-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - monadic-semantic-calculus

# tests:
#   monadic-semantic-calculus-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - monadic-semantic-calculus
